[build]
  command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1 && \
    export PATH="$PATH:`pwd`/flutter/bin" && \
    flutter doctor -v && \
    flutter config --enable-web && \
    flutter build web --release
  """
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
