[build]
  command = "flutter/bin/flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.24.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
